title: "ksanbal blog"
email: "dev.ksanbal@gmail.com"
tagline: "A jekyll theme that looks like a shell/terminal"
description: "This is a preview of jekyll-shell-theme."
github_username: Ksanbal
baseurl: "/"
url: "https://ksanbal.github.io"

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  style: compressed

highlighter: rouge

header_pages:
  - index.md
  - read-me.md
  - preview.md

# set the size of the text to 'large' or 'small', default is small
font-size: large
