title: "ksanbal blog"
email: "dev.ksanbal@gmail.com"
tagline: "A jekyll theme that looks like a shell/terminal"
description: "어제보다 더 좋은 개발자가 되고 싶은 김산발입니다"
baseurl: "/"
url: "https://ksanbal.github.io"

github_username: Ksanbal
linkedin_username: devksanbal

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

sass:
  style: compressed

highlighter: rouge

header_pages:
  - index.md
  - read-me.md
  # - preview.md

# set the size of the text to 'large' or 'small', default is small
font-size: large

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  # 전역적으로 코드 라인 활성화 #
  syntax_highlighter_opts:
    block:
      line_numbers: false
