title: "ksanbal blog"
email: "dev.ksanbal@gmail.com"
tagline: "A jekyll theme that looks like a shell/terminal"
description: "어제보다 더 좋은 개발자가 되고 싶은 김산발입니다"
baseurl: "/"
url: "https://ksanbal.github.io"

github_username: Ksanbal
linkedin_username: devksanbal

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  style: compressed

highlighter: rouge

header_pages:
  - index.md
  - read-me.md
  # - preview.md

# set the size of the text to 'large' or 'small', default is small
font-size: large
